### ISSUE TITLE
Commit Related ghidra 10.2_dev Should be explicitly Spelt Out its Dependency

### ISSUE THREAD

**Issue by LHG** [DSecurity/efiSeek#5]
Commit: 573f4b9b5ba2731cdecafc6594d0fd0570e28fff
Problem:  Currently there are 2 ghidra githubs

1) 10.1.3    => https://github.com/NationalSecurityAgency/ghidra 
     compatible with:     **ntHeader = NTHeader.createNTHeader ....**

2) 10.2dev => https://github.com/garyttierney/ghidra-batteries-included/releases
      compatible with:    **ntHeader = new NTHeader**

The latest commit will break the 10.1.3.  As I'm new to this tool, basically any background sharing about both revision are welcome.

**Comment by retrage** [comment]
Hi, I'm not a member of this repository, but I have proposed the previous PR #3.
As you pointed out, I created the PR changes for Ghidra 10.1.3, which is the latest official release version.
The commit https://github.com/DSecurity/efiSeek/commit/573f4b9b5ba2731cdecafc6594d0fd0570e28fff changes are for Ghidra 10.2dev, which is under development and not an official release. I think the committer uses this plugin with Ghidra nightly build or something patched version internally.
