### ISSUE TITLE
 TransferEfiFilesToProject.java usage

### ISSUE THREAD

**Issue by hanetzer** [DSecurity/efiSeek#7]
I may be dumb here, but exactly how is one supposed to invoke this tool? I've tried passing it a bios file,
a dir containing efi modules, a single efi module, and nothing at all (though I know that's wrong, since
you check for args.length

**Comment by TheJokiv** [comment]
It's a headless script. For starting it you need use something like this:
```
support\analyzeHeadless.bat project_path project_name -import import_folder -recursive -log ./export.log -postScript TransferEfiFilesToProject.java root_folder_inside_project
```

**Comment by hanetzer** [comment]
Yeah I get that is a headless. So, import_folder is a folder containing pre-unpacked efi modules, then?

**Comment by hanetzer** [comment]
Ok got it all figured out, thanks. Now another question. If I were to extend the guids db file, is there a way to 'resort'
the existing non-sorted files in an existing project?

**Comment by TheJokiv** [comment]
You can use `-process folder_in_project -recursive` instead of `-import import_folder -recursive` to reanalyze files in project.
But efiSeek don't check user changes in the files and can ruin them on the second run of the plugin.
